ARDUINO_DIR   = /Applications/Arduino.app/Contents/Java
ARDMK_DIR     = $(HOME)/working/Arduino-Makefile
AVR_TOOLS_DIR = /opt/local
# AVR_TOOLS_DIR = /Applications/Arduino.app/Contents/Java/hardware/tools/avr
MONITOR_PORT  = /dev/cu.wchusbserial14140
BOARD_TAG     = uno
#USER_LIB_PATH = $(HOME)/Documents/Arduino/libraries
ARDUINO_LIBS = SSD1306Ascii-master SPI SD SoftwareSerial Wire

include $(HOME)/working/Arduino-Makefile/Arduino.mk
