ARDUINO_DIR   = /Applications/Arduino.app/Contents/Java
ARDMK_DIR     = /Users/motohisa/working/Arduino-Makefile
AVR_TOOLS_DIR = /opt/local
# AVR_TOOLS_DIR = /Applications/Arduino.app/Contents/Java/hardware/tools/avr
MONITOR_PORT  = /dev/cu.wchusbserial14140
BOARD_TAG     = uno
ARDUINO_LIBS = /Users/motohisa/Documents/Arduino/libraries/SevenSeg-master

include /Users/motohisa/working/Arduino-Makefile/Arduino.mk

# include /Applications/Arduino.app/Contents//Java/hardware/tools/avr/avr/include

# make CPPFLAGS="-I/Applications/Arduino.app/Contents//Java/hardware/tools/avr/avr/include -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino"
